import {
    Document,
    Packer,
    Paragraph,
    TextRun,
    HeadingLevel,
    Table,
    TableRow,
    TableCell,
    WidthType,
    BorderStyle,
    AlignmentType,
    Header,
    Footer,
    PageNumber,
    NumberFormat
} from "docx";
import { saveAs } from "file-saver";
import { Project, UserStory } from "../../types";

export const generateWordReport = async (project: Project) => {
    const sprint = project.phases.sprint;
    const stories = project.phases.backlog?.epics.flatMap((e) => e.stories) || [];
    const activeStories = stories.filter((s) => s.isInSprint);
    const completedStories = activeStories.filter(
        (s) => s.status.toLowerCase() === "done"
    );
    const totalSP = activeStories.reduce((acc, s) => acc + s.storyPoints, 0);
    const doneSP = completedStories.reduce((acc, s) => acc + s.storyPoints, 0);

    // --- STYLES ---
    const titleStyle = {
        font: "Calibri",
        size: 52, // 26pt
        bold: true,
        color: "2E74B5",
    };
    const header1Style = {
        font: "Calibri",
        size: 32, // 16pt
        bold: true,
        color: "1F4D78",
        spaceBefore: 240,
        spaceAfter: 120,
    };
    const header2Style = {
        font: "Calibri",
        size: 28, // 14pt
        bold: true,
        color: "2E74B5",
        spaceBefore: 200,
        spaceAfter: 100,
    };
    const normalStyle = {
        font: "Calibri",
        size: 22, // 11pt
    };

    // --- SECTIONS ---

    // 1. Cover Page
    const coverPage = [
        new Paragraph({
            text: project.name.toUpperCase(),
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
            spacing: { before: 5000, after: 400 },
        }),
        new Paragraph({
            text: "Project Status Report",
            heading: HeadingLevel.HEADING_2,
            alignment: AlignmentType.CENTER,
            spacing: { after: 200 },
        }),
        new Paragraph({
            text: `Date: ${new Date().toLocaleDateString()}`,
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
        }),
        new Paragraph({
            text: `Generated by SCRUM.AI`,
            alignment: AlignmentType.CENTER,
            run: {
                italics: true,
                color: "666666",
                size: 20
            }
        }),
    ];

    // 2. Vision & Strategy
    const visionSection = [
        new Paragraph({
            text: "1. Vision & Strategy",
            heading: HeadingLevel.HEADING_1,
        }),
        createKeyValue("Vision", project.phases.vision?.text || "Not defined"),
        createKeyValue("Objectives", project.phases.objectives?.text || "Not defined"),
        new Paragraph({ text: "Key Performance Indicators (KPIs):", heading: HeadingLevel.HEADING_2 }),
        createTable([
            ["Metric", "Value", "Target"],
            ...(project.phases.kpis?.table?.map((kpi: any) => [
                kpi.metric || "-",
                kpi.current || "-",
                kpi.target || "-"
            ]) || [["No KPIs defined", "-", "-"]])
        ])
    ];

    // 3. Team
    const teamSection = [
        new Paragraph({
            text: "2. Team & Health",
            heading: HeadingLevel.HEADING_1,
            pageBreakBefore: true,
        }),
        new Paragraph({ text: "Team Roster:", heading: HeadingLevel.HEADING_2 }),
        createTable([
            ["Name", "Role", "Availability"],
            ...(project.phases.team?.members.map(m => [
                m.name,
                m.role,
                `${m.availability}%`
            ]) || [["No members", "-", "-"]])
        ]),
        new Paragraph({ text: "", spacing: { after: 200 } }), // Spacer
    ];

    // 4. Execution (Sprint)
    const sprintSection = [
        new Paragraph({
            text: "3. Execution Status (Sprint)",
            heading: HeadingLevel.HEADING_1,
        }),
        createKeyValue("Current Status", sprint?.isActive ? "Active" : "Planning/Completed"),
        createKeyValue("Goal", sprint?.goal || "No Goal Set"),
        createKeyValue("Dates", `${new Date(sprint?.startDate || "").toLocaleDateString()} - ${new Date(sprint?.endDate || "").toLocaleDateString()}`),

        new Paragraph({ text: "Performance Metrics:", heading: HeadingLevel.HEADING_2 }),
        createTable([
            ["Metric", "Value"],
            ["Total Scope (SP)", totalSP.toString()],
            ["Completed (SP)", doneSP.toString()],
            ["Progress", `${Math.round((doneSP / (totalSP || 1)) * 100)}%`],
            ["Stories Done", completedStories.length.toString()],
            ["Throughput (Items)", completedStories.length.toString()],
        ]),
    ];

    // 5. Risks (Obeya)
    const risksSection = [
        new Paragraph({
            text: "4. Risks & Impediments",
            heading: HeadingLevel.HEADING_1,
        }),
        createTable([
            ["Risk Description", "Impact", "Mitigation"],
            ...(project.phases.obeya?.risks.map(r => [
                r.risk,
                r.impact,
                r.mitigation
            ]) || [["No critical risks identified", "-", "-"]])
        ])
    ];

    // --- DOCUMENT ASSEMBLY ---
    const doc = new Document({
        sections: [
            {
                properties: {},
                headers: {
                    default: new Header({
                        children: [
                            new Paragraph({
                                children: [
                                    new TextRun({
                                        text: project.name,
                                        bold: true,
                                    }),
                                    new TextRun({
                                        text: "\t\tconfidential",
                                        italics: true,
                                    })
                                ],
                            }),
                        ],
                    }),
                },
                footers: {
                    default: new Footer({
                        children: [
                            new Paragraph({
                                alignment: AlignmentType.CENTER,
                                children: [
                                    new TextRun({ children: ["Page ", PageNumber.CURRENT] }),
                                    new TextRun({ children: [" of ", PageNumber.TOTAL_PAGES] }),
                                ],
                            }),
                        ],
                    }),
                },
                children: [
                    ...coverPage,
                    ...visionSection,
                    ...teamSection,
                    ...sprintSection,
                    ...risksSection
                ],
            },
        ],
    });

    // Generate and Download
    const buffer = await Packer.toBlob(doc);
    saveAs(buffer, `Project_Report_${project.name.replace(/\s+/g, "_")}_${new Date().toISOString().split('T')[0]}.docx`);
};

// --- HELPERS ---

function createKeyValue(key: string, value: string) {
    return new Paragraph({
        children: [
            new TextRun({ text: `${key}: `, bold: true }),
            new TextRun({ text: value }),
        ],
        spacing: { after: 120 },
    });
}

function createTable(rows: string[][]) {
    return new Table({
        width: {
            size: 100,
            type: WidthType.PERCENTAGE,
        },
        rows: rows.map((row, i) =>
            new TableRow({
                children: row.map(cellText =>
                    new TableCell({
                        children: [new Paragraph({
                            text: cellText,
                            style: i === 0 ? "Header" : undefined // Simple bolding for header
                        })],
                        shading: i === 0 ? { fill: "E0E0E0" } : undefined,
                        margins: { top: 100, bottom: 100, left: 100, right: 100 },
                        borders: {
                            top: { style: BorderStyle.SINGLE, size: 1 },
                            bottom: { style: BorderStyle.SINGLE, size: 1 },
                            left: { style: BorderStyle.SINGLE, size: 1 },
                            right: { style: BorderStyle.SINGLE, size: 1 },
                        }
                    })
                )
            })
        )
    });
}
